id: IFCB7E3DE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:53:29+00:00'
last_modified: '2022-06-07T18:44:18.919769+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8928
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    55FB:
      image_group_id: I1KG9003
      title: ''
      total_pages: 788
      order: 1
      base_file: 55FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
