id: P003265
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8928
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ།
  author: ''
  volumes:
    73a760e41dbc42509c40f29d5d59df1e:
      image_group_id: I1KG9003
      title: ''
      volume_number: 1
      total_pages: 788
      base_file: v001.txt
